# Your personal GitHub token
github_token: 1823903fd8ff776b966a54bc286f5f98b9623308
# Read more: https://github.com/blog/1509-personal-api-tokens
# You can generate it here: https://github.com/settings/tokens

# Guest OS timezone
timezone: Europe/Moscow

# Are we need check box updates for every 'vagrant up'?
box_check_update: false

# Virtual machine name
machine_name: y2aa

# Virtual machine IP
ip: 192.168.83.137

# Virtual machine CPU cores number
cpus: 1

# Virtual machine RAM
memory: 1024
